# Generated by Django 3.1.2 on 2020-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20201029_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_time_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
